# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.
name: schemaorg
version: '0.0.0'
github: "githubuser/schemaorg"
license: MIT
author: "Author name here"
maintainer: "Author name here"
# synopsis: A new Haskeleton package.
# description: schemaorg is a new Haskeleton package.
# category: Other

extra-source-files:
- CHANGELOG.md
- LICENSE.md
- package.yaml
- README.md
- stack.yaml

ghc-options: -Wall

library:
  dependencies:
  - base
  - rdf4h
  - mtl
  - lens
  source-dirs: library

executables:
  schemaorg:
    source-dirs: executable
    main: MainExecutable.hs
    dependencies:
    - base
    - schemaorg
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N

benchmarks:
  schemaorg-benchmarks:
    source-dirs: benchmark
    main: MainExecutable.hs
    dependencies:
    - base
    - schemaorg
    - criterion
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N

tests:
  schemaorg-test-suite:
    source-dirs: test-suite
    main: MainExecutable.hs
    dependencies:
    - base
    - schemaorg
    - tasty
    - tasty-hspec
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
